---
baseurl: "http://systemzoo.org/"
languageCode: "en-us"
title: "SystemZoo"
permalinks:
  post: /:year/:month/:title/
# Additional site configuration
defaultLayout:	"page"
defaultExtension: "html"
paginate: 10
paginatePath: "page"
publishdir: "public"
theme: "flat-zoo"
MetaDataFormat: "yaml"
params:
  Description: "Solving technology problems with friends."
  GithubOrg: systemzoo
  Twitter: systemszoo
  # Google Analytics ID
  GATID: UA-67277032-1
